#!/bin/bash
clear
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install curl -y &>/dev/null
apt install git -y &>/dev/null 
apt install figlet boxes -y &>/dev/null
cd $HOME
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;33mAGUARDE \033[1;37m> \033[1;32m|"
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;32m█"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;32m|"
sleep 1s
tput cuu1
tput dl1
echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;33mAGUARDE \033[1;37m> \033[1;32m|"
done
echo -e "\033[1;32m|\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
apt-get install curl -y &>/dev/null
clear
apt install pv &>/dev/null
clear
apt-get install lolcat -y &>/dev/null
clear
apt-get install figlet -y &>/dev/null
clear
apt-get install curl -y &>/dev/null
clear
apt install git -y &>/dev/null 
apt install figlet boxes -y &>/dev/null 
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo ""
echo -e "\033[1;37m $system                          $date"
figlet ' SSHWEB PRO' | boxes -d stone -p a0v0 | lolcat
echo "CONHECIMENTO NAO E CRIME"
echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
echo ""
echo ""
echo -e "                       \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN  9 x64\033[0m 🐧"
echo -e "\033[1;31m \033[1;33m\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA (V2RAY) EVITEM OUTROS SISTEMAS\033[0m"
echo -e "\033[1;31m \033[1;33m\033[0m"
echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
echo -ne "\033[1;31m╰━━━━━━━━❪\033[1;36mPRECIONE ENTER PRA CONTINUAR (n) SAIR:\033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -ne "\033[1;36mINFORME SUA KEY:\033[1;37m "; read _key_
if [[ -z $_key_ ]]; then
echo ""
echo -e "\033[1;31m KEY INVALIDA\033[1;32m"
sleep 1
clear; exit
fi
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink https://raw.githubusercontent.com/mztp/mztp/master/Install/list > /dev/null 2>&1; verif_key
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
rm versao* > /dev/null 2>&1
wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Install/versao > /dev/null 2>&1
> /dev/null 2>&1
rm v2raymanager > /dev/null 2>&1
wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/v2raymanager > /dev/null 2>&1
wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/botteste.sh >/dev/null 2>&1
chmod 777 v2raymanager > /dev/null 2>&1
chmod 777 botteste.sh > /dev/null 2>&1
mkdir $HOME/BOT >/dev/null 2>&1
cd $HOME/BOT
wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Sistema/ShellBot.sh >/dev/null 2>&1
chmod 777 ShellBot.sh > /dev/null 2>&1
cd > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mTUDO PRONTO! \033[1;32m"
sleep 2s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet ' SSHWEB PRO' | boxes -d stone -p a0v0 | lolcat
echo "CONHECIMENTO NAO E CRIME"
echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
echo -e "\033[1;33mOPA DETECTAMOS..."
echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
echo -e "\033[1;33mDADOS DE USUÁRIOS ENCONTRADO!"
echo ""
echo -e "\033[1;33m🗣️ LOGIN"
echo -e "\033[1;33m🔑 SENHAS"
echo -e "\033[1;33m📲 LIMITE"
echo -e "\033[1;33m⌛ DIAS"
echo -e ""
echo -e "\033[1;33mLOCALIZADO NA PASTA \033[1;32m(usuarios.db)"
echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMANTER DADOS ATUAL\033[0m"
echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCRIAR UMA NOVA BASE DE DADOS\033[0m"
echo -e "\033[01;31m━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━\033[0m"
echo ""
tput setaf 2 ; tput bold ; read -p "Opção ?: " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet "SSHWEB PRO" | lolcat
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                 ATUALIZAÇÕES COSTUMA DEMORAR UM POUCO !               \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m║\033[0m"
fun_attlist () {
apt-get update -y
apt-get install net-tools -y
echo "SSHWEB PRO" > /root/name
echo "V2RAY PRO" >/etc/SSHPlus/RegV2ray
echo "0" > /root/valor
echo "USO INDEVIDO [ON]" > /root/banido
cd /bin/ && rm -f .criar*
cd /bin/ && rm -f .rmuid*
cd /etc/ && rm -f .rmuser*
cd /bin/ && rm -f .uid*
cd /bin/ && rm -f ackclear*
cd /etc/ && rm -f acksyshttpack*
cd /bin/ && rm -f addhost*
cd /bin/ && rm -f ajuda*
cd /etc/ && rm -f alterarlimite*
cd /bin/ && rm -f alterarsenha*
cd /bin/ && rm -f antCrashARM.sh*
cd /etc/ && rm -f apache2menu*
cd /bin/ && rm -f attscript*
cd /bin/ && rm -f Autobackup*
cd /etc/ && rm -f backup_mail.sh*
cd /bin/ && rm -f badpro*
cd /bin/ && rm -f badvpn*
cd /etc/ && rm -f badvpn-udpgw*
cd /bin/ && rm -f banner*
cd /bin/ && rm -f bashtop*
cd /etc/ && rm -f ddos*
cd /bin/ && rm -f blocksite*
cd /bin/ && rm -f blockt*
cd /etc/ && rm -f blockuser*
cd /bin/ && rm -f bot*
cd /bin/ && rm -f botssh*
cd /etc/ && rm -f cabecalho*
cd /bin/ && rm -f celular.sh*
cd /bin/ && rm -f conexao*
cd /etc/ && rm -f criarteste*
cd /bin/ && rm -f criarusuario*
cd /bin/ && rm -f delhost*
cd /etc/ && rm -f delscript*
cd /bin/ && rm -f detalhes*
cd /bin/ && rm -f dns-netflix.sh*
cd /etc/ && rm -f dns-server*
cd /bin/ && rm -f droplimiter*
cd /bin/ && rm -f expcleaner*
cd /etc/ && rm -f ban.sh*
cd /bin/ && rm -f fail2ban*
cd /bin/ && rm -f fr*
cd /bin/ && rm -f haveged*
cd /etc/ && rm -f infousers*
cd /bin/ && rm -f initbot*
cd /bin/ && rm -f inst-botteste*
cd /etc/ && rm -f instsqd*
cd /bin/ && rm -f limiter*
cd /bin/ && rm -f listARM*
cd /etc/ && rm -f menu*
cd /bin/ && rm -f mudardata*
cd /bin/ && rm -f multi*
cd /etc/ && rm -f onlineapp*
cd /bin/ && rm -f open.py*
cd /bin/ && rm -f otimizar*
cd /etc/ && rm -f painelv2ray*
cd /bin/ && rm -f prissh*
cd /bin/ && rm -f prnet.sh*
cd /etc/ && rm -f proxy.py*
cd /bin/ && rm -f reiniciarservicos*
cd /bin/ && rm -f reiniciarsistema*
cd /etc/ && rm -f remove-slow*
cd /bin/ && rm -f remover*
cd /bin/ && rm -f restartdns*
cd /etc/ && rm -f senharoot*
cd /bin/ && rm -f ShellBot.sh*
cd /bin/ && rm -f slow_dns*
cd /etc/ && rm -f slowdns*
cd /bin/ && rm -f slowdns-drop*
cd /bin/ && rm -f slowdns-info*
cd /etc/ && rm -f slowdns-socks*
cd /bin/ && rm -f slowdns-ssh*
cd /bin/ && rm -f slowdns-ssl*
cd /etc/ && rm -f speedtest*
cd /bin/ && rm -f sshmonitor*
cd /bin/ && rm -f startdns*
cd /etc/ && rm -f stopdns*
cd /etc/ && rm -f mtuning*
cd /bin/ && rm -f swapmemory*
cd /bin/ && rm -f trojan-go*
cd /etc/ && rm -f tuning*
cd /bin/ && rm -f tweaker*
cd /bin/ && rm -f uexpired*
cd /etc/ && rm -f userbackup*
cd /bin/ && rm -f v2ray*
cd /bin/ && rm -f v2raymanager*
cd /etc/ && rm -f verifatt*
cd /bin/ && rm -f verifbot*
cd /bin/ && rm -f webmin.sh*
cd /etc/ && rm -f websocket.sh*
cd /bin/ && rm -f wsproxy.py*
cd /etc/ && rm -f rc.local
cd /etc/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/rc.local > /dev/null 2>&1
cd /etc/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/fr > /dev/null 2>&1 
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/.criar > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/mtuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/.rmuid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/.rmuser > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/.uid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/ackclear > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/acksyshttpack > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/addhost > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/ajuda > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/alterarlimite > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/alterarsenha > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/antCrashARM.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/apache2menu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/attscript > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/Autobackup > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/backup_mail.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/badpro > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/badvpn > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/badvpn-udpgw > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/banner > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/bashtop > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/ddos > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/blocksite > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/blockt > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/blockuser > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/bot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/botssh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/cabecalho > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/celular.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/conexao > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/criarteste > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/criarusuario > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/delhost > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/delscript > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/detalhes > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/dns-netflix.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/dns-server > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/droplimiter > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/expcleaner > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/ban.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/fail2ban > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/haveged > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/infousers > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/initbot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/bashtop > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/ShellBot.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/botteste > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/inst-botteste > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/inst-botteste > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/instsqd > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/limiter > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/listARM > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/menu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/mudardata > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/multi > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/onlineapp > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/open.py > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/otimizar > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/painelv2ray > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/prissh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/prnet.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/proxy.py > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/reiniciarservicos > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/reiniciarsistema > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/remove-slow > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/remover > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/restartdns > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/senharoot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/ShellBot.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slow_dns > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slowdns > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slowdns-drop > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slowdns-info > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slowdns-socks > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slowdns-ssh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slowdns-ssl > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/speedtest > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/sshmonitor > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/startdns > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/stopdns > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/swapmemory > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/trojan-go > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/tuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/tweaker > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/uexpired > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/userbackup > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/v2ray > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/v2raymanager > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/verifatt > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/verifbot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/webmin.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/websocket.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/wsproxy.py > /dev/null 2>&1
cd /etc/ && chmod +x .criar
cd /etc/ && chmod +x .rmuid
cd /bin/ && chmod +x .uid
cd /bin/ && chmod +x ackclear
cd /bin/ && chmod +x acksyshttpack
cd /bin/ && chmod +x addhost
cd /bin/ && chmod +x ajuda
cd /bin/ && chmod +x alterarlimite
cd /bin/ && chmod +x alterarsenha
cd /bin/ && chmod +x antCrashARM.sh
cd /bin/ && chmod +x apache2menu
cd /bin/ && chmod +x attscript
cd /bin/ && chmod +x Autobackup
cd /bin/ && chmod +x backup_mail.sh
cd /bin/ && chmod +x badpro
cd /bin/ && chmod +x badvpn
cd /bin/ && chmod +x badvpn-udpgw
cd /bin/ && chmod +x banner
cd /bin/ && chmod +x bashtop
cd /bin/ && chmod +x ddos
cd /bin/ && chmod +x blocksite
cd /bin/ && chmod +x blockt
cd /bin/ && chmod +x blockuser
cd /bin/ && chmod +x bot
cd /bin/ && chmod +x botssh
cd /bin/ && chmod +x cabecalho
cd /bin/ && chmod +x celular.sh
cd /bin/ && chmod +x conexao
cd /bin/ && chmod +x criarteste
cd /bin/ && chmod +x criarusuario
cd /bin/ && chmod +x delhost
cd /bin/ && chmod +x delscript
cd /etc/ && chmod +x detalhes
cd /etc/ && chmod +x dns-netflix.sh
cd /bin/ && chmod +x dns-server
cd /bin/ && chmod +x droplimiter
cd /bin/ && chmod +x expcleaner
cd /bin/ && chmod +x ban.sh
cd /bin/ && chmod +x fail2ban
cd /bin/ && chmod +x fr
cd /bin/ && chmod +x haveged
cd /bin/ && chmod +x infousers
cd /bin/ && chmod +x initbot
cd /bin/ && chmod +x inst-botteste
cd /bin/ && chmod +x instsqd
cd /bin/ && chmod +x limiter
cd /bin/ && chmod +x listARM
cd /bin/ && chmod +x menu
cd /bin/ && chmod +x mudardata
cd /bin/ && chmod +x mtuning
cd /bin/ && chmod +x multi
cd /bin/ && chmod +x onlineapp
cd /bin/ && chmod +x open.py
cd /bin/ && chmod +x otimizar
cd /bin/ && chmod +x painelv2ray
cd /bin/ && chmod +x prissh
cd /bin/ && chmod +x prnet.sh
cd /bin/ && chmod +x proxy.py
cd /bin/ && chmod +x reiniciarservicos
cd /bin/ && chmod +x reiniciarsistema
cd /bin/ && chmod +x remove-slow
cd /bin/ && chmod +x remover
cd /bin/ && chmod +x restartdns
cd /bin/ && chmod +x senharoot
cd /bin/ && chmod +x ShellBot.sh
cd /bin/ && chmod +x slow_dns
cd /etc/ && chmod +x slowdns
cd /etc/ && chmod +x slowdns-drop
cd /bin/ && chmod +x slowdns-info
cd /bin/ && chmod +x slowdns-socks
cd /bin/ && chmod +x slowdns-ssh
cd /bin/ && chmod +x slowdns-ssl
cd /bin/ && chmod +x speedtest
cd /bin/ && chmod +x sshmonitor
cd /bin/ && chmod +x startdns
cd /bin/ && chmod +x stopdns
cd /bin/ && chmod +x swapmemory
cd /bin/ && chmod +x trojan-go
cd /bin/ && chmod +x tuning
cd /bin/ && chmod +x tweaker
cd /bin/ && chmod +x uexpired
cd /bin/ && chmod +x userbackup
cd /bin/ && chmod +x v2ray
cd /bin/ && chmod +x v2raymanager
cd /bin/ && chmod +x verifatt
cd /bin/ && chmod +x verifbot
cd /bin/ && chmod +x webmin.sh
cd /bin/ && chmod +x websocket.sh
cd /bin/ && chmod +x wsproxy.py
cd /bin/ && rm -f slowdns*
cd /bin/ && wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/Modulos/slowdns > /dev/null 2>&1
cd /bin/ && chmod +x slowdns
rm -rf install; wget https://raw.githubusercontent.com/Couty-SSH/01_PRO/main/slowdns/install; chmod +x install; ./install
[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet "    SSHWEB PRO" | lolcat
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                 ATUALIZAÇÃO DE PACOTES NECESSÁRIOS                \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m║\033[0m"
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet "    SSHWEB PRO" | lolcat
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                FINALIZANDO INSTALAÇÕES NECESSÁRIAS               \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m║\033[0m"
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
clear
echo ""
cd $HOME
  echo "clear" >>/root/.bashrc
  echo 'DATE=$(date +"%d-%m-%y")' >>/root/.bashrc
  echo 'TIME=$(date +"%T")' >>/root/.bashrc
  echo 'figlet -k SSHWEB PRO | lolcat' >>/root/.bashrc
  echo 'echo -e " NOME DO SERVIDOR : $HOSTNAME"' >>/root/.bashrc
  echo 'echo -e " SERVIDOR LIGADO À : $(uptime -p)"' >>/root/.bashrc
  echo 'echo -e " DATA : $DATE"' >>/root/.bashrc
  echo 'echo -e " HORA : $TIME"' >>/root/.bashrc
  echo 'echo -e "@Couty_SSH"' >>.bashrc
  echo 'echo -e "\033[1;31m DIGITE ( menu ) PARA ENTRAR\033[0m."' >>/root/.bashrc
  echo 'echo -e ""' >>/root/.bashrc
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo -e "\033[1;37m $system                          $date"
figlet "SSHWEB PRO" | lolcat
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                INSTALACAO CONCLUIDA               \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m║\033[1;33mPARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
echo -e "\033[01;31m║\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@Couty_SSH\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
