#!/bin/bash
clear
varDir="bancodir"
rm /var/www/html/admin/pages/apis/$varDir/plus.sql > /dev/null 2>&1
senha=$(cat /var/www/html/pages/system/pass.php |cut -d"'" -f2)
mysqldump -u root -p$senha plus > /var/www/html/admin/pages/apis/$varDir/plus.sql
